print("hello \"iam\" pratyush")
print('hello i\'am pratyush')
print("hello\niam pratyush")
print("hello\tiam pratyush")
print("this is backslash\\")
print("this is double backslash\\\\")
print("helll\bo")